### ISSUE TITLE
Open PR for LAB 2.

### ISSUE THREAD

**Issue by ASV44** [ivyana/PAM#3]
@ivyana please open PR for LAB 2 and implement required changes for LAB 1 PR and after that ping me in order to check your PRs

**Comment by ASV44** [comment]
@ivyana why did you close this issue?
I didn't see any PR for lab 2. No PR for lab 2 means -1 point to mark. 
If we will consider submission date as date of latest commit on lab No 2 branch which is 12th March, this means that max mark for lab No. 2 is 8 because you submitted it 2 weeks after. No PR means mark for lab No. 2 will be 7

**Comment by ivyana** [comment]
@ASV44 I have submitted lab 1 and lab 2 on time, you can check teams messages. I had some problems with opening PRs because I created new projects for each lab, instead of working in the same project(different commit histories). I tried to delete those branches and reupload them, just before 1st attestation, that is why the date is 12th March. I solved the problem and created 2 new branches for lab 1 and 2 with PRs. Can I delete the old ones?
